# Automatically generated Python configuration

CONFIG = {   'canvas': {'height': 170, 'pixel': 'RGB16_565', 'width': 320},
    'debug_update': False,
    'device': '1-8:1.1',
    'heartbeat': 60000,
    'led_config': {'device': '/dev/ttyUSB0', 'intensity': 3, 'speed': 3, 'theme': 5},
    'listen': '0.0.0.0:1234',
    'poll': 300,
    'portrait': True,
    'refresh': 1600,
    'sensors': [   {'module': 'sensors/clock.js'},
                   {'module': 'sensors/calendar.js'},
                   {'config': {'max_points': 300}, 'module': 'sensors/cpu_usage.js'},
                   {'config': {'fahrenheit': True, 'max_points': 300}, 'module': 'sensors/cpu_temp.js'},
                   {'config': {'max_points': 300}, 'module': 'sensors/cpu_power.js'},
                   {'config': {'interface': 'enp2s0', 'max_points': 300}, 'module': 'sensors/network.js'},
                   {'config': {'interface': 'enp4s0', 'max_points': 300}, 'module': 'sensors/network.js'},
                   {'config': {'max_points': 300}, 'module': 'sensors/memory.js'},
                   {'config': {'max_points': 300, 'mount_point': '/', 'name': 'root'}, 'module': 'sensors/space.js'},
                   {   'config': {'country': 'US', 'forecast': 0, 'imperial': True, 'name': 'nyc'},
                       'module': 'sensors/weather.js'},
                   {   'config': {'country': 'US', 'forecast': 1, 'imperial': True, 'name': 'nyc'},
                       'module': 'sensors/weather.js'}],
    'theme': 'app/themes/agni_dark/agni_dark.py',
    'theme_list': [   {'config': 'app/themes/agni_dark/agni_dark.py', 'name': 'Agni Dark — Cyberpunk'},
                      {'config': 'app/themes/simple_demo/portrait_simple.py', 'name': 'Simple Demo (Portrait)'}],
    'widgets': [   'widgets/text.js',
                   'widgets/custom_bar.js',
                   'widgets/line_chart.js',
                   'widgets/doughnut_chart.js',
                   'widgets/bar_chart.js',
                   'widgets/image.js',
                   'widgets/iconify.js',
                   'widgets/weather_icon.js']}
