# Automatically generated Python screen

SCREEN = {   'background': '#040608',
    'id': 3,
    'led_config': {'intensity': 2, 'speed': 2, 'theme': 3},
    'name': 'Clock & Date',
    'widgets': [   {   'align': 'center',
                       'color': '#2a4060',
                       'debug_frame': False,
                       'font': 'bold 18px Arial',
                       'format': '{6}',
                       'group': 1,
                       'id': 1,
                       'name': 'text',
                       'rect': {'height': 20, 'width': 170, 'x': 0, 'y': 8},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'calendar'},
                   {   'align': 'center',
                       'color': '#00d4ff',
                       'debug_frame': False,
                       'font': 'bold 52px Arial',
                       'format': '{1}',
                       'group': 1,
                       'id': 2,
                       'name': 'text',
                       'rect': {'height': 60, 'width': 170, 'x': 0, 'y': 60},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'clock'},
                   {   'align': 'center',
                       'color': '#a855f7',
                       'debug_frame': False,
                       'font': 'bold 20px Arial',
                       'format': '{3}',
                       'group': 1,
                       'id': 3,
                       'name': 'text',
                       'rect': {'height': 22, 'width': 170, 'x': 0, 'y': 122},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'clock'},
                   {   'align': 'center',
                       'color': '#f59e0b',
                       'debug_frame': False,
                       'font': 'bold 26px Arial',
                       'format': '{3}',
                       'group': 2,
                       'id': 4,
                       'name': 'text',
                       'rect': {'height': 30, 'width': 170, 'x': 0, 'y': 158},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'calendar'},
                   {   'align': 'center',
                       'color': '#e2e8f0',
                       'debug_frame': False,
                       'font': 'bold 28px Arial',
                       'format': '{4}',
                       'group': 2,
                       'id': 5,
                       'name': 'text',
                       'rect': {'height': 32, 'width': 170, 'x': 0, 'y': 190},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'calendar'},
                   {   'align': 'center',
                       'color': '#4a6080',
                       'debug_frame': False,
                       'font': '18px Arial',
                       'format': '{9}/{2}/{10}',
                       'group': 2,
                       'id': 6,
                       'name': 'text',
                       'rect': {'height': 22, 'width': 170, 'x': 0, 'y': 224},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'calendar'},
                   {   'area': True,
                       'debug_frame': False,
                       'fill': 'rgba(0,212,255,0.12)',
                       'format': '{1}',
                       'group': 3,
                       'id': 7,
                       'name': 'line_chart',
                       'outline': '#00d4ff',
                       'points': 30,
                       'rect': {'height': 40, 'width': 85, 'x': 0, 'y': 255},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'cpu_usage'},
                   {   'align': 'center',
                       'color': '#00d4ff',
                       'debug_frame': False,
                       'font': '9px Arial',
                       'format': 'CPU {0}%',
                       'group': 3,
                       'id': 8,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 85, 'x': 0, 'y': 296},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'cpu_usage'},
                   {   'area': True,
                       'debug_frame': False,
                       'fill': 'rgba(16,185,129,0.12)',
                       'format': '{1}',
                       'group': 4,
                       'id': 9,
                       'name': 'line_chart',
                       'outline': '#10b981',
                       'points': 30,
                       'rect': {'height': 40, 'width': 85, 'x': 85, 'y': 255},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'cpu_temp'},
                   {   'align': 'center',
                       'color': '#10b981',
                       'debug_frame': False,
                       'font': '9px Arial',
                       'format': 'TEMP {0}{2}',
                       'group': 4,
                       'id': 10,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 85, 'x': 85, 'y': 296},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'cpu_temp'},
                   {   'align': 'center',
                       'color': '#2a3d55',
                       'debug_frame': False,
                       'font': '9px Arial',
                       'format': 'â†“{15}  â†‘{16}',
                       'group': 5,
                       'id': 11,
                       'name': 'text',
                       'rect': {'height': 10, 'width': 170, 'x': 0, 'y': 310},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'network_enp4s0'}]}
