# Automatically generated Python screen

SCREEN = {   'background': '#060a10',
    'id': 2,
    'led_config': {'intensity': 2, 'speed': 3, 'theme': 1},
    'name': 'Network & Charts',
    'widgets': [   {   'align': 'center',
                       'color': '#00d4ff',
                       'debug_frame': False,
                       'font': 'bold 11px Arial',
                       'format': '',
                       'group': 1,
                       'id': 1,
                       'name': 'text',
                       'rect': {'height': 13, 'width': 170, 'x': 0, 'y': 3},
                       'refresh': 0,
                       'sensor': False,
                       'value': 'NETWORK'},
                   {   'area': True,
                       'debug_frame': False,
                       'fill': 'rgba(0,212,255,0.15)',
                       'format': '{2}',
                       'group': 2,
                       'id': 2,
                       'name': 'line_chart',
                       'outline': '#00d4ff',
                       'points': 60,
                       'rect': {'height': 55, 'width': 170, 'x': 0, 'y': 18},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'network_enp4s0'},
                   {   'align': 'left',
                       'color': '#00d4ff',
                       'debug_frame': False,
                       'font': 'bold 10px Arial',
                       'format': '',
                       'group': 2,
                       'id': 3,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 50, 'x': 2, 'y': 74},
                       'refresh': 0,
                       'sensor': False,
                       'value': 'â†“ RX'},
                   {   'align': 'right',
                       'color': '#00d4ff',
                       'debug_frame': False,
                       'font': 'bold 10px Arial',
                       'format': '{15}',
                       'group': 2,
                       'id': 4,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 88, 'x': 80, 'y': 74},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'network_enp4s0'},
                   {   'area': True,
                       'debug_frame': False,
                       'fill': 'rgba(244,114,182,0.15)',
                       'format': '{5}',
                       'group': 3,
                       'id': 5,
                       'name': 'line_chart',
                       'outline': '#f472b6',
                       'points': 60,
                       'rect': {'height': 55, 'width': 170, 'x': 0, 'y': 90},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'network_enp4s0'},
                   {   'align': 'left',
                       'color': '#f472b6',
                       'debug_frame': False,
                       'font': 'bold 10px Arial',
                       'format': '',
                       'group': 3,
                       'id': 6,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 50, 'x': 2, 'y': 146},
                       'refresh': 0,
                       'sensor': False,
                       'value': 'â†‘ TX'},
                   {   'align': 'right',
                       'color': '#f472b6',
                       'debug_frame': False,
                       'font': 'bold 10px Arial',
                       'format': '{16}',
                       'group': 3,
                       'id': 7,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 88, 'x': 80, 'y': 146},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'network_enp4s0'},
                   {   'align': 'center',
                       'color': '#2a4060',
                       'debug_frame': False,
                       'font': 'bold 10px Arial',
                       'format': '',
                       'group': 4,
                       'id': 8,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 170, 'x': 0, 'y': 163},
                       'refresh': 0,
                       'sensor': False,
                       'value': 'CPU  TREND'},
                   {   'debug_frame': False,
                       'fill': '#0077aa',
                       'format': '{1}',
                       'group': 4,
                       'id': 9,
                       'name': 'bar_chart',
                       'outline': '#00d4ff',
                       'points': 16,
                       'rect': {'height': 40, 'width': 170, 'x': 0, 'y': 176},
                       'refresh': 1000,
                       'sensor': True,
                       'thickness': 8,
                       'value': 'cpu_usage',
                       'zoom': 2},
                   {   'align': 'right',
                       'color': '#00d4ff',
                       'debug_frame': False,
                       'font': 'bold 10px Arial',
                       'format': '{0}%',
                       'group': 4,
                       'id': 10,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 38, 'x': 130, 'y': 217},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'cpu_usage'},
                   {   'align': 'center',
                       'color': '#2a4060',
                       'debug_frame': False,
                       'font': 'bold 10px Arial',
                       'format': '',
                       'group': 5,
                       'id': 11,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 170, 'x': 0, 'y': 232},
                       'refresh': 0,
                       'sensor': False,
                       'value': 'TEMPERATURE  TREND'},
                   {   'debug_frame': False,
                       'fill': '#076b46',
                       'format': '{1}',
                       'group': 5,
                       'id': 12,
                       'name': 'bar_chart',
                       'outline': '#10b981',
                       'points': 16,
                       'rect': {'height': 40, 'width': 170, 'x': 0, 'y': 245},
                       'refresh': 1000,
                       'sensor': True,
                       'thickness': 8,
                       'value': 'cpu_temp',
                       'zoom': 2},
                   {   'align': 'right',
                       'color': '#10b981',
                       'debug_frame': False,
                       'font': 'bold 10px Arial',
                       'format': '{0}{2}',
                       'group': 5,
                       'id': 13,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 38, 'x': 130, 'y': 286},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'cpu_temp'},
                   {   'align': 'center',
                       'color': '#2a4060',
                       'debug_frame': False,
                       'font': '11px Arial',
                       'format': '{1} {3}',
                       'group': 6,
                       'id': 14,
                       'name': 'text',
                       'rect': {'height': 14, 'width': 170, 'x': 0, 'y': 304},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'clock'}]}
