# Automatically generated Python screen

SCREEN = {
    'background': '#09090b',
    'id': 5,
    'led_config': {'intensity': 4, 'speed': 3, 'theme': 4},
    'name': 'Performance Dashboard',
    'widgets': [
        {
            'align': 'center',
            'color': '#38bdf8',
            'debug_frame': False,
            'font': 'bold 16px Arial',
            'format': 'PERFORMANCE',
            'group': 1,
            'id': 1,
            'name': 'text',
            'rect': {'height': 20, 'width': 170, 'x': 0, 'y': 10},
            'refresh': 0,
            'sensor': False,
            'value': ''
        },
        {
            'debug_frame': False,
            'format': '{0}',
            'free': '#2e1025',
            'group': 2,
            'id': 2,
            'name': 'doughnut_chart',
            'rect': {'height': 60, 'width': 60, 'x': 20, 'y': 40},
            'refresh': 1000,
            'sensor': True,
            'used': '#f43f5e',
            'value': 'cpu_usage'
        },
        {
            'align': 'center',
            'color': '#f43f5e',
            'debug_frame': False,
            'font': 'bold 12px Arial',
            'format': '{0}%',
            'group': 2,
            'id': 3,
            'name': 'text',
            'rect': {'height': 15, 'width': 60, 'x': 20, 'y': 62},
            'refresh': 1000,
            'sensor': True,
            'value': 'cpu_usage'
        },
        {
            'align': 'center',
            'color': '#881337',
            'debug_frame': False,
            'font': 'bold 10px Arial',
            'format': 'CPU',
            'group': 2,
            'id': 4,
            'name': 'text',
            'rect': {'height': 12, 'width': 60, 'x': 20, 'y': 105},
            'refresh': 0,
            'sensor': False,
            'value': ''
        },
        {
            'debug_frame': False,
            'format': '{2}',
            'free': '#1c0f2e',
            'group': 3,
            'id': 5,
            'name': 'doughnut_chart',
            'rect': {'height': 60, 'width': 60, 'x': 90, 'y': 40},
            'refresh': 1000,
            'sensor': True,
            'used': '#a855f7',
            'value': 'memory'
        },
        {
            'align': 'center',
            'color': '#a855f7',
            'debug_frame': False,
            'font': 'bold 12px Arial',
            'format': '{2}%',
            'group': 3,
            'id': 6,
            'name': 'text',
            'rect': {'height': 15, 'width': 60, 'x': 90, 'y': 62},
            'refresh': 1000,
            'sensor': True,
            'value': 'memory'
        },
        {
            'align': 'center',
            'color': '#4c1d95',
            'debug_frame': False,
            'font': 'bold 10px Arial',
            'format': 'RAM',
            'group': 3,
            'id': 7,
            'name': 'text',
            'rect': {'height': 12, 'width': 60, 'x': 90, 'y': 105},
            'refresh': 0,
            'sensor': False,
            'value': ''
        },
        {
            'debug_frame': False,
            'fill': '#064e3b',
            'format': '{1}',
            'group': 4,
            'horizontal': True,
            'id': 8,
            'name': 'bar_chart',
            'outline': '#10b981',
            'points': 1,
            'rect': {'height': 20, 'width': 150, 'x': 10, 'y': 125},
            'refresh': 1000,
            'sensor': True,
            'thickness': 150,
            'value': 'cpu_temp',
            'zoom': 0
        },
        {
            'align': 'left',
            'color': '#ffffff',
            'debug_frame': False,
            'font': 'bold 11px Arial',
            'format': 'TEMP: {0}{2}',
            'group': 4,
            'id': 9,
            'name': 'text',
            'rect': {'height': 16, 'width': 140, 'x': 15, 'y': 127},
            'refresh': 1000,
            'sensor': True,
            'value': 'cpu_temp'
        },
        {
            'debug_frame': False,
            'fill': '#78350f',
            'format': '{1}',
            'group': 5,
            'horizontal': True,
            'id': 10,
            'name': 'bar_chart',
            'outline': '#f59e0b',
            'points': 1,
            'rect': {'height': 20, 'width': 150, 'x': 10, 'y': 155},
            'refresh': 1000,
            'sensor': True,
            'thickness': 150,
            'value': 'cpu_power',
            'zoom': 0
        },
        {
            'align': 'left',
            'color': '#ffffff',
            'debug_frame': False,
            'font': 'bold 11px Arial',
            'format': 'PWR: {0}W',
            'group': 5,
            'id': 11,
            'name': 'text',
            'rect': {'height': 16, 'width': 140, 'x': 15, 'y': 157},
            'refresh': 1000,
            'sensor': True,
            'value': 'cpu_power'
        },
        {
            'area': True,
            'debug_frame': False,
            'fill': 'rgba(244,63,94,0.2)',
            'format': '{1}',
            'group': 6,
            'id': 12,
            'name': 'line_chart',
            'outline': '#f43f5e',
            'points': 60,
            'rect': {'height': 50, 'width': 170, 'x': 0, 'y': 190},
            'refresh': 1000,
            'sensor': True,
            'value': 'cpu_usage'
        },
        {
            'area': True,
            'debug_frame': False,
            'fill': 'rgba(168,85,247,0.2)',
            'format': '{3}',
            'group': 7,
            'id': 13,
            'name': 'line_chart',
            'outline': '#a855f7',
            'points': 60,
            'rect': {'height': 50, 'width': 170, 'x': 0, 'y': 250},
            'refresh': 1000,
            'sensor': True,
            'value': 'memory'
        },
        {
            'align': 'right',
            'color': '#4c1d95',
            'debug_frame': False,
            'font': '9px Arial',
            'format': 'v1.0 AGNI SYSTEM',
            'group': 8,
            'id': 14,
            'name': 'text',
            'rect': {'height': 14, 'width': 160, 'x': 0, 'y': 305},
            'refresh': 0,
            'sensor': False,
            'value': ''
        }
    ]
}
