# Automatically generated Python screen

SCREEN = {   'background': '#060a10',
    'id': 4,
    'led_config': {'intensity': 2, 'speed': 2, 'theme': 5},
    'name': 'Storage & Power',
    'widgets': [   {   'align': 'center',
                       'color': '#00d4ff',
                       'debug_frame': False,
                       'font': 'bold 11px Arial',
                       'format': '',
                       'group': 1,
                       'id': 1,
                       'name': 'text',
                       'rect': {'height': 14, 'width': 170, 'x': 0, 'y': 3},
                       'refresh': 0,
                       'sensor': False,
                       'value': 'STORAGE & POWER'},
                   {   'debug_frame': False,
                       'format': '{0}',
                       'free': '#1a1200',
                       'group': 2,
                       'id': 2,
                       'name': 'doughnut_chart',
                       'rect': {'height': 70, 'width': 70, 'x': 10, 'y': 18},
                       'refresh': 1000,
                       'sensor': True,
                       'used': '#f59e0b',
                       'value': 'cpu_power'},
                   {   'align': 'center',
                       'color': '#f59e0b',
                       'debug_frame': False,
                       'font': 'bold 12px Arial',
                       'format': '{0}W',
                       'group': 2,
                       'id': 3,
                       'name': 'text',
                       'rect': {'height': 14, 'width': 70, 'x': 10, 'y': 48},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'cpu_power'},
                   {   'align': 'center',
                       'color': '#2a4060',
                       'debug_frame': False,
                       'font': 'bold 9px Arial',
                       'format': '',
                       'group': 2,
                       'id': 4,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 70, 'x': 10, 'y': 86},
                       'refresh': 0,
                       'sensor': False,
                       'value': 'CPU PWR'},
                   {   'debug_frame': False,
                       'format': '{4}',
                       'free': '#200a0a',
                       'group': 3,
                       'id': 5,
                       'name': 'doughnut_chart',
                       'rect': {'height': 70, 'width': 70, 'x': 90, 'y': 18},
                       'refresh': 1000,
                       'sensor': True,
                       'used': '#ef4444',
                       'value': 'space'},
                   {   'align': 'center',
                       'color': '#ef4444',
                       'debug_frame': False,
                       'font': 'bold 12px Arial',
                       'format': '{4}%',
                       'group': 3,
                       'id': 6,
                       'name': 'text',
                       'rect': {'height': 14, 'width': 70, 'x': 90, 'y': 48},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'space'},
                   {   'align': 'center',
                       'color': '#2a4060',
                       'debug_frame': False,
                       'font': '9px Arial',
                       'format': '{5} MiB free',
                       'group': 3,
                       'id': 7,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 70, 'x': 90, 'y': 86},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'space'},
                   {   'area': True,
                       'debug_frame': False,
                       'fill': 'rgba(245,158,11,0.15)',
                       'format': '{1}',
                       'group': 4,
                       'id': 8,
                       'name': 'line_chart',
                       'outline': '#f59e0b',
                       'points': 60,
                       'rect': {'height': 50, 'width': 170, 'x': 0, 'y': 102},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'cpu_power'},
                   {   'align': 'center',
                       'color': '#f59e0b',
                       'debug_frame': False,
                       'font': '9px Arial',
                       'format': 'PWR  {0} W',
                       'group': 4,
                       'id': 9,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 166, 'x': 2, 'y': 152},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'cpu_power'},
                   {   'align': 'center',
                       'color': '#2a4060',
                       'debug_frame': False,
                       'font': 'bold 9px Arial',
                       'format': '',
                       'group': 5,
                       'id': 10,
                       'name': 'text',
                       'rect': {'height': 11, 'width': 170, 'x': 0, 'y': 170},
                       'refresh': 0,
                       'sensor': False,
                       'value': 'MEMORY BREAKDOWN'},
                   {   'debug_frame': False,
                       'fill': '#7c3aed',
                       'format': '{10}',
                       'group': 5,
                       'horizontal': True,
                       'id': 11,
                       'name': 'bar_chart',
                       'outline': '#a855f7',
                       'points': 1,
                       'rect': {'height': 20, 'width': 170, 'x': 0, 'y': 183},
                       'refresh': 1000,
                       'sensor': True,
                       'thickness': 170,
                       'value': 'memory',
                       'zoom': 0},
                   {   'align': 'left',
                       'color': '#ffffff',
                       'debug_frame': False,
                       'font': 'bold 11px Arial',
                       'format': 'Used: {14}',
                       'group': 5,
                       'id': 12,
                       'name': 'text',
                       'rect': {'height': 16, 'width': 160, 'x': 5, 'y': 184},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'memory'},
                   {   'debug_frame': False,
                       'fill': '#b91c1c',
                       'format': '{12}',
                       'group': 5,
                       'horizontal': True,
                       'id': 13,
                       'name': 'bar_chart',
                       'outline': '#ef4444',
                       'points': 1,
                       'rect': {'height': 20, 'width': 170, 'x': 0, 'y': 207},
                       'refresh': 1000,
                       'sensor': True,
                       'thickness': 170,
                       'value': 'memory',
                       'zoom': 0},
                   {   'align': 'left',
                       'color': '#ffffff',
                       'debug_frame': False,
                       'font': 'bold 11px Arial',
                       'format': 'Swap: {15}',
                       'group': 5,
                       'id': 14,
                       'name': 'text',
                       'rect': {'height': 16, 'width': 160, 'x': 5, 'y': 208},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'memory'},
                   {   'align': 'center',
                       'color': '#2a4060',
                       'debug_frame': False,
                       'font': 'bold 9px Arial',
                       'format': '',
                       'group': 6,
                       'id': 15,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 170, 'x': 0, 'y': 235},
                       'refresh': 0,
                       'sensor': False,
                       'value': 'CPU TEMP TREND'},
                   {   'area': True,
                       'debug_frame': False,
                       'fill': 'rgba(16,185,129,0.15)',
                       'format': '{1}',
                       'group': 6,
                       'id': 16,
                       'name': 'line_chart',
                       'outline': '#10b981',
                       'points': 60,
                       'rect': {'height': 50, 'width': 170, 'x': 0, 'y': 248},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'cpu_temp'},
                   {   'align': 'center',
                       'color': '#10b981',
                       'debug_frame': False,
                       'font': '9px Arial',
                       'format': 'TEMP  {0}{2}',
                       'group': 6,
                       'id': 17,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 166, 'x': 2, 'y': 299},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'cpu_temp'},
                   {   'align': 'center',
                       'color': '#1a2d44',
                       'debug_frame': False,
                       'font': '9px Arial',
                       'format': '{1} {3}',
                       'group': 7,
                       'id': 18,
                       'name': 'text',
                       'rect': {'height': 10, 'width': 170, 'x': 0, 'y': 313},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'clock'}]}
