# Automatically generated Python screen

SCREEN = {   'background': '#060a10',
    'id': 1,
    'led_config': {'intensity': 3, 'speed': 2, 'theme': 2},
    'name': 'System Status',
    'widgets': [   {   'align': 'center',
                       'color': '#00d4ff',
                       'debug_frame': False,
                       'font': 'bold 12px Arial',
                       'format': '{1} {3}',
                       'group': 1,
                       'id': 1,
                       'name': 'text',
                       'rect': {'height': 14, 'width': 170, 'x': 0, 'y': 3},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'clock'},
                   {   'align': 'right',
                       'color': '#4a6080',
                       'debug_frame': False,
                       'font': '10px Arial',
                       'format': '{6} {9}/{2}/{10}',
                       'group': 1,
                       'id': 2,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 170, 'x': 0, 'y': 3},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'calendar'},
                   {   'debug_frame': False,
                       'format': '{0}',
                       'free': '#0d1e2d',
                       'group': 2,
                       'id': 3,
                       'name': 'doughnut_chart',
                       'rect': {'height': 80, 'width': 80, 'x': 10, 'y': 20},
                       'refresh': 1000,
                       'sensor': True,
                       'used': '#00d4ff',
                       'value': 'cpu_usage'},
                   {   'align': 'center',
                       'color': '#00d4ff',
                       'debug_frame': False,
                       'font': 'bold 14px Arial',
                       'format': '{0}%',
                       'group': 2,
                       'id': 4,
                       'name': 'text',
                       'rect': {'height': 16, 'width': 80, 'x': 10, 'y': 55},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'cpu_usage'},
                   {   'align': 'center',
                       'color': '#2a4060',
                       'debug_frame': False,
                       'font': 'bold 10px Arial',
                       'format': '',
                       'group': 2,
                       'id': 5,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 80, 'x': 10, 'y': 97},
                       'refresh': 0,
                       'sensor': False,
                       'value': 'CPU'},
                   {   'debug_frame': False,
                       'format': '{2}',
                       'free': '#1a0d2e',
                       'group': 3,
                       'id': 6,
                       'name': 'doughnut_chart',
                       'rect': {'height': 80, 'width': 80, 'x': 90, 'y': 20},
                       'refresh': 1000,
                       'sensor': True,
                       'used': '#a855f7',
                       'value': 'memory'},
                   {   'align': 'center',
                       'color': '#a855f7',
                       'debug_frame': False,
                       'font': 'bold 14px Arial',
                       'format': '{2}%',
                       'group': 3,
                       'id': 7,
                       'name': 'text',
                       'rect': {'height': 16, 'width': 80, 'x': 90, 'y': 55},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'memory'},
                   {   'align': 'center',
                       'color': '#2a4060',
                       'debug_frame': False,
                       'font': '9px Arial',
                       'format': '{14}',
                       'group': 3,
                       'id': 8,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 80, 'x': 90, 'y': 97},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'memory'},
                   {   'debug_frame': False,
                       'format': '{0}',
                       'free': '#0a2018',
                       'group': 4,
                       'id': 9,
                       'name': 'doughnut_chart',
                       'rect': {'height': 80, 'width': 80, 'x': 10, 'y': 112},
                       'refresh': 1000,
                       'sensor': True,
                       'used': '#10b981',
                       'value': 'cpu_temp'},
                   {   'align': 'center',
                       'color': '#10b981',
                       'debug_frame': False,
                       'font': 'bold 13px Arial',
                       'format': '{0}{2}',
                       'group': 4,
                       'id': 10,
                       'name': 'text',
                       'rect': {'height': 16, 'width': 80, 'x': 10, 'y': 147},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'cpu_temp'},
                   {   'align': 'center',
                       'color': '#2a4060',
                       'debug_frame': False,
                       'font': 'bold 10px Arial',
                       'format': '',
                       'group': 4,
                       'id': 11,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 80, 'x': 10, 'y': 190},
                       'refresh': 0,
                       'sensor': False,
                       'value': 'TEMP'},
                   {   'debug_frame': False,
                       'format': '{0}',
                       'free': '#1a1200',
                       'group': 5,
                       'id': 12,
                       'name': 'doughnut_chart',
                       'rect': {'height': 80, 'width': 80, 'x': 90, 'y': 112},
                       'refresh': 1000,
                       'sensor': True,
                       'used': '#f59e0b',
                       'value': 'cpu_power'},
                   {   'align': 'center',
                       'color': '#f59e0b',
                       'debug_frame': False,
                       'font': 'bold 13px Arial',
                       'format': '{0}W',
                       'group': 5,
                       'id': 13,
                       'name': 'text',
                       'rect': {'height': 16, 'width': 80, 'x': 90, 'y': 147},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'cpu_power'},
                   {   'align': 'center',
                       'color': '#2a4060',
                       'debug_frame': False,
                       'font': 'bold 10px Arial',
                       'format': '',
                       'group': 5,
                       'id': 14,
                       'name': 'text',
                       'rect': {'height': 12, 'width': 80, 'x': 90, 'y': 190},
                       'refresh': 0,
                       'sensor': False,
                       'value': 'POWER'},
                   {   'area': True,
                       'debug_frame': False,
                       'fill': 'rgba(0,212,255,0.2)',
                       'format': '{1}',
                       'group': 6,
                       'id': 15,
                       'name': 'line_chart',
                       'outline': '#00d4ff',
                       'points': 60,
                       'rect': {'height': 35, 'width': 170, 'x': 0, 'y': 205},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'cpu_usage'},
                   {   'align': 'left',
                       'color': '#00d4ff',
                       'debug_frame': False,
                       'font': '9px Arial',
                       'format': 'CPU {0}%',
                       'group': 6,
                       'id': 16,
                       'name': 'text',
                       'rect': {'height': 11, 'width': 80, 'x': 2, 'y': 241},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'cpu_usage'},
                   {   'area': True,
                       'debug_frame': False,
                       'fill': 'rgba(168,85,247,0.2)',
                       'format': '{3}',
                       'group': 7,
                       'id': 17,
                       'name': 'line_chart',
                       'outline': '#a855f7',
                       'points': 60,
                       'rect': {'height': 35, 'width': 170, 'x': 0, 'y': 255},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'memory'},
                   {   'align': 'left',
                       'color': '#a855f7',
                       'debug_frame': False,
                       'font': '9px Arial',
                       'format': 'MEM {2}%  {14}',
                       'group': 7,
                       'id': 18,
                       'name': 'text',
                       'rect': {'height': 11, 'width': 100, 'x': 2, 'y': 291},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'memory'},
                   {   'align': 'center',
                       'color': '#4a7090',
                       'debug_frame': False,
                       'font': '10px Arial',
                       'format': 'â†“{15}  â†‘{16}',
                       'group': 8,
                       'id': 19,
                       'name': 'text',
                       'rect': {'height': 14, 'width': 170, 'x': 0, 'y': 305},
                       'refresh': 1000,
                       'sensor': True,
                       'value': 'network_enp4s0'}]}
