# Automatically generated Python screen

SCREEN = {
    'background': '#0f172a',
    'id': 6,
    'led_config': {'intensity': 2, 'speed': 1, 'theme': 1},
    'name': 'Zen Weather Time',
    'widgets': [
        {
            'align': 'center',
            'color': '#e2e8f0',
            'debug_frame': False,
            'font': 'bold 48px Arial',
            'format': '{1}',
            'group': 1,
            'id': 1,
            'name': 'text',
            'rect': {'height': 55, 'width': 170, 'x': 0, 'y': 40},
            'refresh': 1000,
            'sensor': True,
            'value': 'clock'
        },
        {
            'align': 'center',
            'color': '#94a3b8',
            'debug_frame': False,
            'font': 'bold 16px Arial',
            'format': '{3}',
            'group': 1,
            'id': 2,
            'name': 'text',
            'rect': {'height': 18, 'width': 170, 'x': 0, 'y': 95},
            'refresh': 1000,
            'sensor': True,
            'value': 'clock'
        },
        {
            'align': 'center',
            'color': '#38bdf8',
            'debug_frame': False,
            'font': 'bold 18px Arial',
            'format': '{7} {2}, {8}',
            'group': 2,
            'id': 3,
            'name': 'text',
            'rect': {'height': 20, 'width': 170, 'x': 0, 'y': 118},
            'refresh': 1000,
            'sensor': True,
            'value': 'calendar'
        },
        {
            'align': 'center',
            'color': '#475569',
            'debug_frame': False,
            'font': 'italic 12px Arial',
            'format': '{4}',
            'group': 2,
            'id': 4,
            'name': 'text',
            'rect': {'height': 14, 'width': 170, 'x': 0, 'y': 140},
            'refresh': 1000,
            'sensor': True,
            'value': 'calendar'
        },
        {
            'debug_frame': False,
            'format': '{4}',
            'free': '#022c22',
            'group': 3,
            'id': 5,
            'name': 'doughnut_chart',
            'rect': {'height': 80, 'width': 80, 'x': 45, 'y': 180},
            'refresh': 1000,
            'sensor': True,
            'used': '#10b981',
            'value': 'space'
        },
        {
            'align': 'center',
            'color': '#10b981',
            'debug_frame': False,
            'font': 'bold 16px Arial',
            'format': '{4}%',
            'group': 3,
            'id': 6,
            'name': 'text',
            'rect': {'height': 18, 'width': 80, 'x': 45, 'y': 211},
            'refresh': 1000,
            'sensor': True,
            'value': 'space'
        },
        {
            'align': 'center',
            'color': '#64748b',
            'debug_frame': False,
            'font': 'bold 12px Arial',
            'format': 'SYSTEM STORAGE',
            'group': 3,
            'id': 7,
            'name': 'text',
            'rect': {'height': 14, 'width': 170, 'x': 0, 'y': 270},
            'refresh': 0,
            'sensor': False,
            'value': ''
        },
        {
            'align': 'center',
            'color': '#334155',
            'debug_frame': False,
            'font': '9px Arial',
            'format': 'Free: {5} MB',
            'group': 3,
            'id': 8,
            'name': 'text',
            'rect': {'height': 12, 'width': 170, 'x': 0, 'y': 288},
            'refresh': 1000,
            'sensor': True,
            'value': 'space'
        }
    ]
}
