# Automatically converted from JSON

THEME = {   'orientation': 'portrait',
    'refresh': 'update',
    'screens': [   {   'background': '#060a10',
                       'id': 1,
                       'led_config': {'intensity': 3, 'speed': 2, 'theme': 2},
                       'name': 'System Status',
                       'widgets': [   {   'align': 'center',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': 'bold 12px Arial',
                                          'format': '{1} {3}',
                                          'group': 1,
                                          'id': 1,
                                          'name': 'text',
                                          'rect': {'height': 14, 'width': 170, 'x': 0, 'y': 3},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'clock'},
                                      {   'align': 'right',
                                          'color': '#4a6080',
                                          'debug_frame': False,
                                          'font': '10px Arial',
                                          'format': '{6} {9}/{2}/{10}',
                                          'group': 1,
                                          'id': 2,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 170, 'x': 0, 'y': 3},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'calendar'},
                                      {   'debug_frame': False,
                                          'format': '{0}',
                                          'free': '#0d1e2d',
                                          'group': 2,
                                          'id': 3,
                                          'name': 'doughnut_chart',
                                          'rect': {'height': 80, 'width': 80, 'x': 10, 'y': 20},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'used': '#00d4ff',
                                          'value': 'cpu_usage'},
                                      {   'align': 'center',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': 'bold 14px Arial',
                                          'format': '{0}%',
                                          'group': 2,
                                          'id': 4,
                                          'name': 'text',
                                          'rect': {'height': 16, 'width': 80, 'x': 10, 'y': 55},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_usage'},
                                      {   'align': 'center',
                                          'color': '#2a4060',
                                          'debug_frame': False,
                                          'font': 'bold 10px Arial',
                                          'format': '',
                                          'group': 2,
                                          'id': 5,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 80, 'x': 10, 'y': 97},
                                          'refresh': 0,
                                          'sensor': False,
                                          'value': 'CPU'},
                                      {   'debug_frame': False,
                                          'format': '{2}',
                                          'free': '#1a0d2e',
                                          'group': 3,
                                          'id': 6,
                                          'name': 'doughnut_chart',
                                          'rect': {'height': 80, 'width': 80, 'x': 90, 'y': 20},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'used': '#a855f7',
                                          'value': 'memory'},
                                      {   'align': 'center',
                                          'color': '#a855f7',
                                          'debug_frame': False,
                                          'font': 'bold 14px Arial',
                                          'format': '{2}%',
                                          'group': 3,
                                          'id': 7,
                                          'name': 'text',
                                          'rect': {'height': 16, 'width': 80, 'x': 90, 'y': 55},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'memory'},
                                      {   'align': 'center',
                                          'color': '#2a4060',
                                          'debug_frame': False,
                                          'font': '9px Arial',
                                          'format': '{14}',
                                          'group': 3,
                                          'id': 8,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 80, 'x': 90, 'y': 97},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'memory'},
                                      {   'debug_frame': False,
                                          'format': '{0}',
                                          'free': '#0a2018',
                                          'group': 4,
                                          'id': 9,
                                          'name': 'doughnut_chart',
                                          'rect': {'height': 80, 'width': 80, 'x': 10, 'y': 112},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'used': '#10b981',
                                          'value': 'cpu_temp'},
                                      {   'align': 'center',
                                          'color': '#10b981',
                                          'debug_frame': False,
                                          'font': 'bold 13px Arial',
                                          'format': '{0}{2}',
                                          'group': 4,
                                          'id': 10,
                                          'name': 'text',
                                          'rect': {'height': 16, 'width': 80, 'x': 10, 'y': 147},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_temp'},
                                      {   'align': 'center',
                                          'color': '#2a4060',
                                          'debug_frame': False,
                                          'font': 'bold 10px Arial',
                                          'format': '',
                                          'group': 4,
                                          'id': 11,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 80, 'x': 10, 'y': 190},
                                          'refresh': 0,
                                          'sensor': False,
                                          'value': 'TEMP'},
                                      {   'debug_frame': False,
                                          'format': '{0}',
                                          'free': '#1a1200',
                                          'group': 5,
                                          'id': 12,
                                          'name': 'doughnut_chart',
                                          'rect': {'height': 80, 'width': 80, 'x': 90, 'y': 112},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'used': '#f59e0b',
                                          'value': 'cpu_power'},
                                      {   'align': 'center',
                                          'color': '#f59e0b',
                                          'debug_frame': False,
                                          'font': 'bold 13px Arial',
                                          'format': '{0}W',
                                          'group': 5,
                                          'id': 13,
                                          'name': 'text',
                                          'rect': {'height': 16, 'width': 80, 'x': 90, 'y': 147},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_power'},
                                      {   'align': 'center',
                                          'color': '#2a4060',
                                          'debug_frame': False,
                                          'font': 'bold 10px Arial',
                                          'format': '',
                                          'group': 5,
                                          'id': 14,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 80, 'x': 90, 'y': 190},
                                          'refresh': 0,
                                          'sensor': False,
                                          'value': 'POWER'},
                                      {   'area': True,
                                          'debug_frame': False,
                                          'fill': 'rgba(0,212,255,0.2)',
                                          'format': '{1}',
                                          'group': 6,
                                          'id': 15,
                                          'name': 'line_chart',
                                          'outline': '#00d4ff',
                                          'points': 60,
                                          'rect': {'height': 35, 'width': 170, 'x': 0, 'y': 205},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_usage'},
                                      {   'align': 'left',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': '9px Arial',
                                          'format': 'CPU {0}%',
                                          'group': 6,
                                          'id': 16,
                                          'name': 'text',
                                          'rect': {'height': 11, 'width': 80, 'x': 2, 'y': 241},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_usage'},
                                      {   'area': True,
                                          'debug_frame': False,
                                          'fill': 'rgba(168,85,247,0.2)',
                                          'format': '{3}',
                                          'group': 7,
                                          'id': 17,
                                          'name': 'line_chart',
                                          'outline': '#a855f7',
                                          'points': 60,
                                          'rect': {'height': 35, 'width': 170, 'x': 0, 'y': 255},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'memory'},
                                      {   'align': 'left',
                                          'color': '#a855f7',
                                          'debug_frame': False,
                                          'font': '9px Arial',
                                          'format': 'MEM {2}%  {14}',
                                          'group': 7,
                                          'id': 18,
                                          'name': 'text',
                                          'rect': {'height': 11, 'width': 100, 'x': 2, 'y': 291},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'memory'},
                                      {   'align': 'center',
                                          'color': '#4a7090',
                                          'debug_frame': False,
                                          'font': '10px Arial',
                                          'format': '↓{15}  ↑{16}',
                                          'group': 8,
                                          'id': 19,
                                          'name': 'text',
                                          'rect': {'height': 14, 'width': 170, 'x': 0, 'y': 305},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'network_enp4s0'}]},
                   {   'background': '#060a10',
                       'duration': 60000,
                       'id': 2,
                       'led_config': {'intensity': 2, 'speed': 3, 'theme': 1},
                       'name': 'Network & Charts',
                       'widgets': [   {   'align': 'center',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': 'bold 11px Arial',
                                          'format': '',
                                          'group': 1,
                                          'id': 1,
                                          'name': 'text',
                                          'rect': {'height': 13, 'width': 170, 'x': 0, 'y': 3},
                                          'refresh': 0,
                                          'sensor': False,
                                          'value': 'NETWORK'},
                                      {   'area': True,
                                          'debug_frame': False,
                                          'fill': 'rgba(0,212,255,0.15)',
                                          'format': '{2}',
                                          'group': 2,
                                          'id': 2,
                                          'name': 'line_chart',
                                          'outline': '#00d4ff',
                                          'points': 60,
                                          'rect': {'height': 55, 'width': 170, 'x': 0, 'y': 18},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'network_enp4s0'},
                                      {   'align': 'left',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': 'bold 10px Arial',
                                          'format': '',
                                          'group': 2,
                                          'id': 3,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 50, 'x': 2, 'y': 74},
                                          'refresh': 0,
                                          'sensor': False,
                                          'value': '↓ RX'},
                                      {   'align': 'right',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': 'bold 10px Arial',
                                          'format': '{15}',
                                          'group': 2,
                                          'id': 4,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 88, 'x': 80, 'y': 74},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'network_enp4s0'},
                                      {   'area': True,
                                          'debug_frame': False,
                                          'fill': 'rgba(244,114,182,0.15)',
                                          'format': '{5}',
                                          'group': 3,
                                          'id': 5,
                                          'name': 'line_chart',
                                          'outline': '#f472b6',
                                          'points': 60,
                                          'rect': {'height': 55, 'width': 170, 'x': 0, 'y': 90},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'network_enp4s0'},
                                      {   'align': 'left',
                                          'color': '#f472b6',
                                          'debug_frame': False,
                                          'font': 'bold 10px Arial',
                                          'format': '',
                                          'group': 3,
                                          'id': 6,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 50, 'x': 2, 'y': 146},
                                          'refresh': 0,
                                          'sensor': False,
                                          'value': '↑ TX'},
                                      {   'align': 'right',
                                          'color': '#f472b6',
                                          'debug_frame': False,
                                          'font': 'bold 10px Arial',
                                          'format': '{16}',
                                          'group': 3,
                                          'id': 7,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 88, 'x': 80, 'y': 146},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'network_enp4s0'},
                                      {   'align': 'center',
                                          'color': '#2a4060',
                                          'debug_frame': False,
                                          'font': 'bold 10px Arial',
                                          'format': '',
                                          'group': 4,
                                          'id': 8,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 170, 'x': 0, 'y': 163},
                                          'refresh': 0,
                                          'sensor': False,
                                          'value': 'CPU  TREND'},
                                      {   'debug_frame': False,
                                          'fill': '#0077aa',
                                          'format': '{1}',
                                          'group': 4,
                                          'id': 9,
                                          'name': 'bar_chart',
                                          'outline': '#00d4ff',
                                          'points': 16,
                                          'rect': {'height': 40, 'width': 170, 'x': 0, 'y': 176},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'thickness': 8,
                                          'value': 'cpu_usage',
                                          'zoom': 2},
                                      {   'align': 'right',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': 'bold 10px Arial',
                                          'format': '{0}%',
                                          'group': 4,
                                          'id': 10,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 38, 'x': 130, 'y': 217},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_usage'},
                                      {   'align': 'center',
                                          'color': '#2a4060',
                                          'debug_frame': False,
                                          'font': 'bold 10px Arial',
                                          'format': '',
                                          'group': 5,
                                          'id': 11,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 170, 'x': 0, 'y': 232},
                                          'refresh': 0,
                                          'sensor': False,
                                          'value': 'TEMPERATURE  TREND'},
                                      {   'debug_frame': False,
                                          'fill': '#076b46',
                                          'format': '{1}',
                                          'group': 5,
                                          'id': 12,
                                          'name': 'bar_chart',
                                          'outline': '#10b981',
                                          'points': 16,
                                          'rect': {'height': 40, 'width': 170, 'x': 0, 'y': 245},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'thickness': 8,
                                          'value': 'cpu_temp',
                                          'zoom': 2},
                                      {   'align': 'right',
                                          'color': '#10b981',
                                          'debug_frame': False,
                                          'font': 'bold 10px Arial',
                                          'format': '{0}{2}',
                                          'group': 5,
                                          'id': 13,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 38, 'x': 130, 'y': 286},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_temp'},
                                      {   'align': 'center',
                                          'color': '#2a4060',
                                          'debug_frame': False,
                                          'font': '11px Arial',
                                          'format': '{1} {3}',
                                          'group': 6,
                                          'id': 14,
                                          'name': 'text',
                                          'rect': {'height': 14, 'width': 170, 'x': 0, 'y': 304},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'clock'}]},
                   {   'background': '#040608',
                       'duration': 60000,
                       'id': 3,
                       'led_config': {'intensity': 2, 'speed': 2, 'theme': 3},
                       'name': 'Clock & Date',
                       'widgets': [   {   'align': 'center',
                                          'color': '#2a4060',
                                          'debug_frame': False,
                                          'font': 'bold 18px Arial',
                                          'format': '{6}',
                                          'group': 1,
                                          'id': 1,
                                          'name': 'text',
                                          'rect': {'height': 20, 'width': 170, 'x': 0, 'y': 8},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'calendar'},
                                      {   'align': 'center',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': 'bold 52px Arial',
                                          'format': '{1}',
                                          'group': 1,
                                          'id': 2,
                                          'name': 'text',
                                          'rect': {'height': 60, 'width': 170, 'x': 0, 'y': 60},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'clock'},
                                      {   'align': 'center',
                                          'color': '#a855f7',
                                          'debug_frame': False,
                                          'font': 'bold 20px Arial',
                                          'format': '{3}',
                                          'group': 1,
                                          'id': 3,
                                          'name': 'text',
                                          'rect': {'height': 22, 'width': 170, 'x': 0, 'y': 122},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'clock'},
                                      {   'align': 'center',
                                          'color': '#f59e0b',
                                          'debug_frame': False,
                                          'font': 'bold 26px Arial',
                                          'format': '{3}',
                                          'group': 2,
                                          'id': 4,
                                          'name': 'text',
                                          'rect': {'height': 30, 'width': 170, 'x': 0, 'y': 158},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'calendar'},
                                      {   'align': 'center',
                                          'color': '#e2e8f0',
                                          'debug_frame': False,
                                          'font': 'bold 28px Arial',
                                          'format': '{4}',
                                          'group': 2,
                                          'id': 5,
                                          'name': 'text',
                                          'rect': {'height': 32, 'width': 170, 'x': 0, 'y': 190},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'calendar'},
                                      {   'align': 'center',
                                          'color': '#4a6080',
                                          'debug_frame': False,
                                          'font': '18px Arial',
                                          'format': '{9}/{2}/{10}',
                                          'group': 2,
                                          'id': 6,
                                          'name': 'text',
                                          'rect': {'height': 22, 'width': 170, 'x': 0, 'y': 224},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'calendar'},
                                      {   'area': True,
                                          'debug_frame': False,
                                          'fill': 'rgba(0,212,255,0.12)',
                                          'format': '{1}',
                                          'group': 3,
                                          'id': 7,
                                          'name': 'line_chart',
                                          'outline': '#00d4ff',
                                          'points': 30,
                                          'rect': {'height': 40, 'width': 85, 'x': 0, 'y': 255},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_usage'},
                                      {   'align': 'center',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': '9px Arial',
                                          'format': 'CPU {0}%',
                                          'group': 3,
                                          'id': 8,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 85, 'x': 0, 'y': 296},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_usage'},
                                      {   'area': True,
                                          'debug_frame': False,
                                          'fill': 'rgba(16,185,129,0.12)',
                                          'format': '{1}',
                                          'group': 4,
                                          'id': 9,
                                          'name': 'line_chart',
                                          'outline': '#10b981',
                                          'points': 30,
                                          'rect': {'height': 40, 'width': 85, 'x': 85, 'y': 255},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_temp'},
                                      {   'align': 'center',
                                          'color': '#10b981',
                                          'debug_frame': False,
                                          'font': '9px Arial',
                                          'format': 'TEMP {0}{2}',
                                          'group': 4,
                                          'id': 10,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 85, 'x': 85, 'y': 296},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_temp'},
                                      {   'align': 'center',
                                          'color': '#2a3d55',
                                          'debug_frame': False,
                                          'font': '9px Arial',
                                          'format': '↓{15}  ↑{16}',
                                          'group': 5,
                                          'id': 11,
                                          'name': 'text',
                                          'rect': {'height': 10, 'width': 170, 'x': 0, 'y': 310},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'network_enp4s0'}]},
                   {   'background': '#060a10',
                       'duration': 60000,
                       'id': 4,
                       'led_config': {'intensity': 2, 'speed': 2, 'theme': 5},
                       'name': 'Storage & Power',
                       'widgets': [   {   'align': 'center',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': 'bold 11px Arial',
                                          'format': '',
                                          'group': 1,
                                          'id': 1,
                                          'name': 'text',
                                          'rect': {'height': 14, 'width': 170, 'x': 0, 'y': 3},
                                          'refresh': 0,
                                          'sensor': False,
                                          'value': 'STORAGE & POWER'},
                                      {   'debug_frame': False,
                                          'format': '{0}',
                                          'free': '#1a1200',
                                          'group': 2,
                                          'id': 2,
                                          'name': 'doughnut_chart',
                                          'rect': {'height': 70, 'width': 70, 'x': 10, 'y': 18},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'used': '#f59e0b',
                                          'value': 'cpu_power'},
                                      {   'align': 'center',
                                          'color': '#f59e0b',
                                          'debug_frame': False,
                                          'font': 'bold 12px Arial',
                                          'format': '{0}W',
                                          'group': 2,
                                          'id': 3,
                                          'name': 'text',
                                          'rect': {'height': 14, 'width': 70, 'x': 10, 'y': 48},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_power'},
                                      {   'align': 'center',
                                          'color': '#2a4060',
                                          'debug_frame': False,
                                          'font': 'bold 9px Arial',
                                          'format': '',
                                          'group': 2,
                                          'id': 4,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 70, 'x': 10, 'y': 86},
                                          'refresh': 0,
                                          'sensor': False,
                                          'value': 'CPU PWR'},
                                      {   'debug_frame': False,
                                          'format': '{4}',
                                          'free': '#200a0a',
                                          'group': 3,
                                          'id': 5,
                                          'name': 'doughnut_chart',
                                          'rect': {'height': 70, 'width': 70, 'x': 90, 'y': 18},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'used': '#ef4444',
                                          'value': 'space'},
                                      {   'align': 'center',
                                          'color': '#ef4444',
                                          'debug_frame': False,
                                          'font': 'bold 12px Arial',
                                          'format': '{4}%',
                                          'group': 3,
                                          'id': 6,
                                          'name': 'text',
                                          'rect': {'height': 14, 'width': 70, 'x': 90, 'y': 48},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'space'},
                                      {   'align': 'center',
                                          'color': '#2a4060',
                                          'debug_frame': False,
                                          'font': '9px Arial',
                                          'format': '{5} MiB free',
                                          'group': 3,
                                          'id': 7,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 70, 'x': 90, 'y': 86},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'space'},
                                      {   'area': True,
                                          'debug_frame': False,
                                          'fill': 'rgba(245,158,11,0.15)',
                                          'format': '{1}',
                                          'group': 4,
                                          'id': 8,
                                          'name': 'line_chart',
                                          'outline': '#f59e0b',
                                          'points': 60,
                                          'rect': {'height': 50, 'width': 170, 'x': 0, 'y': 102},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_power'},
                                      {   'align': 'center',
                                          'color': '#f59e0b',
                                          'debug_frame': False,
                                          'font': '9px Arial',
                                          'format': 'PWR  {0} W',
                                          'group': 4,
                                          'id': 9,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 166, 'x': 2, 'y': 152},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_power'},
                                      {   'align': 'center',
                                          'color': '#2a4060',
                                          'debug_frame': False,
                                          'font': 'bold 9px Arial',
                                          'format': '',
                                          'group': 5,
                                          'id': 10,
                                          'name': 'text',
                                          'rect': {'height': 11, 'width': 170, 'x': 0, 'y': 170},
                                          'refresh': 0,
                                          'sensor': False,
                                          'value': 'MEMORY BREAKDOWN'},
                                      {   'debug_frame': False,
                                          'fill': '#7c3aed',
                                          'format': '{10}',
                                          'group': 5,
                                          'horizontal': True,
                                          'id': 11,
                                          'name': 'bar_chart',
                                          'outline': '#a855f7',
                                          'points': 1,
                                          'rect': {'height': 20, 'width': 170, 'x': 0, 'y': 183},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'thickness': 170,
                                          'value': 'memory',
                                          'zoom': 0},
                                      {   'align': 'left',
                                          'color': '#ffffff',
                                          'debug_frame': False,
                                          'font': 'bold 11px Arial',
                                          'format': 'Used: {14}',
                                          'group': 5,
                                          'id': 12,
                                          'name': 'text',
                                          'rect': {'height': 16, 'width': 160, 'x': 5, 'y': 184},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'memory'},
                                      {   'debug_frame': False,
                                          'fill': '#b91c1c',
                                          'format': '{12}',
                                          'group': 5,
                                          'horizontal': True,
                                          'id': 13,
                                          'name': 'bar_chart',
                                          'outline': '#ef4444',
                                          'points': 1,
                                          'rect': {'height': 20, 'width': 170, 'x': 0, 'y': 207},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'thickness': 170,
                                          'value': 'memory',
                                          'zoom': 0},
                                      {   'align': 'left',
                                          'color': '#ffffff',
                                          'debug_frame': False,
                                          'font': 'bold 11px Arial',
                                          'format': 'Swap: {15}',
                                          'group': 5,
                                          'id': 14,
                                          'name': 'text',
                                          'rect': {'height': 16, 'width': 160, 'x': 5, 'y': 208},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'memory'},
                                      {   'align': 'center',
                                          'color': '#2a4060',
                                          'debug_frame': False,
                                          'font': 'bold 9px Arial',
                                          'format': '',
                                          'group': 6,
                                          'id': 15,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 170, 'x': 0, 'y': 235},
                                          'refresh': 0,
                                          'sensor': False,
                                          'value': 'CPU TEMP TREND'},
                                      {   'area': True,
                                          'debug_frame': False,
                                          'fill': 'rgba(16,185,129,0.15)',
                                          'format': '{1}',
                                          'group': 6,
                                          'id': 16,
                                          'name': 'line_chart',
                                          'outline': '#10b981',
                                          'points': 60,
                                          'rect': {'height': 50, 'width': 170, 'x': 0, 'y': 248},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_temp'},
                                      {   'align': 'center',
                                          'color': '#10b981',
                                          'debug_frame': False,
                                          'font': '9px Arial',
                                          'format': 'TEMP  {0}{2}',
                                          'group': 6,
                                          'id': 17,
                                          'name': 'text',
                                          'rect': {'height': 12, 'width': 166, 'x': 2, 'y': 299},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_temp'},
                                      {   'align': 'center',
                                          'color': '#1a2d44',
                                          'debug_frame': False,
                                          'font': '9px Arial',
                                          'format': '{1} {3}',
                                          'group': 7,
                                          'id': 18,
                                          'name': 'text',
                                          'rect': {'height': 10, 'width': 170, 'x': 0, 'y': 313},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'clock'}]}]}
