# Automatically converted from JSON

THEME = {   'orientation': 'portrait',
    'refresh': 'update',
    'screens': [   {   'background': '#000000',
                       'duration': 60000,
                       'id': 1,
                       'led_config': {'intensity': 3, 'speed': 3, 'theme': 4},
                       'name': 'Screen 1',
                       'widgets': [   {   'debug_frame': False,
                                          'format': '{0}',
                                          'free': '#0d1e2d',
                                          'group': 1,
                                          'id': 1,
                                          'name': 'doughnut_chart',
                                          'rect': {'height': 100, 'width': 100, 'x': 35, 'y': 0},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'used': '#00d4ff',
                                          'value': 'cpu_usage'},
                                      {   'color': '#4a6080',
                                          'debug_frame': False,
                                          'group': 1,
                                          'iconSet': 'mdi',
                                          'id': 2,
                                          'name': 'iconify',
                                          'rect': {'height': 50, 'width': 50, 'x': 60, 'y': 30},
                                          'refresh': 0,
                                          'sensor': False,
                                          'value': 'memory'},
                                      {   'debug_frame': False,
                                          'format': '{0}',
                                          'free': '#0d1e2d',
                                          'group': 2,
                                          'id': 3,
                                          'name': 'doughnut_chart',
                                          'rect': {'height': 100, 'width': 100, 'x': 35, 'y': 102},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'used': '#00d4ff',
                                          'value': 'cpu_temp'},
                                      {   'color': '#4a6080',
                                          'debug_frame': False,
                                          'group': 2,
                                          'iconSet': 'mdi',
                                          'id': 4,
                                          'name': 'iconify',
                                          'rect': {'height': 50, 'width': 50, 'x': 60, 'y': 135},
                                          'refresh': 0,
                                          'sensor': False,
                                          'value': 'temperature-lines'},
                                      {   'debug_frame': False,
                                          'format': '{0}',
                                          'free': '#0d1e2d',
                                          'group': 3,
                                          'id': 5,
                                          'name': 'doughnut_chart',
                                          'rect': {'height': 100, 'width': 100, 'x': 35, 'y': 205},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'used': '#00d4ff',
                                          'value': 'cpu_power'},
                                      {   'color': '#4a6080',
                                          'debug_frame': False,
                                          'group': 3,
                                          'iconSet': 'mdi',
                                          'id': 6,
                                          'name': 'iconify',
                                          'rect': {'height': 50, 'width': 50, 'x': 60, 'y': 238},
                                          'refresh': 0,
                                          'sensor': False,
                                          'value': 'lightbulb'},
                                      {   'align': 'center',
                                          'color': '#4a6080',
                                          'debug_frame': False,
                                          'font': '17px Arial',
                                          'format': '{0}%',
                                          'group': 1,
                                          'id': 7,
                                          'name': 'text',
                                          'rect': {'height': 25, 'width': 45, 'x': 65, 'y': 81},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_usage'},
                                      {   'align': 'center',
                                          'color': '#4a6080',
                                          'debug_frame': False,
                                          'font': '17px Arial',
                                          'format': '{0} {2}',
                                          'group': 2,
                                          'id': 8,
                                          'name': 'text',
                                          'rect': {'height': 24, 'width': 47, 'x': 62, 'y': 187},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_temp'},
                                      {   'align': 'center',
                                          'color': '#4a6080',
                                          'debug_frame': False,
                                          'font': '17px Arial',
                                          'format': '{0} W',
                                          'group': 3,
                                          'id': 9,
                                          'name': 'text',
                                          'rect': {'height': 21, 'width': 53, 'x': 59, 'y': 290},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_power'},
                                      {   'align': 'left',
                                          'color': '#10b981',
                                          'debug_frame': False,
                                          'font': '13px Arial',
                                          'format': '{1} {3}',
                                          'group': 1,
                                          'id': 10,
                                          'name': 'text',
                                          'rect': {'height': 17, 'width': 60, 'x': 0, 'y': 0},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'clock'},
                                      {   'align': 'right',
                                          'color': '#10b981',
                                          'debug_frame': False,
                                          'font': '13px Arial',
                                          'format': '{9}/{2}/{10}',
                                          'group': 1,
                                          'id': 11,
                                          'name': 'text',
                                          'rect': {'height': 17, 'width': 60, 'x': 110, 'y': 0},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'calendar'},
                                      {   'align': 'center',
                                          'color': '#10b981',
                                          'debug_frame': False,
                                          'font': '10px Arial',
                                          'format': '{17}',
                                          'group': 1,
                                          'id': 12,
                                          'name': 'text',
                                          'rect': {'height': 10, 'width': 50, 'x': 0, 'y': 310},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'network_enp4s0'}]},
                   {   'background': '#000000',
                       'duartion': 0,
                       'duration': 60000,
                       'id': 2,
                       'led_config': {'intensity': 3, 'speed': 3, 'theme': 2},
                       'name': 'Screen 2 Charts',
                       'widgets': [   {   'area': True,
                                          'debug_frame': False,
                                          'fill': '#004466',
                                          'format': '{1}',
                                          'group': 1,
                                          'id': 1,
                                          'name': 'line_chart',
                                          'outline': '#00d4ff',
                                          'points': 60,
                                          'rect': {'height': 25, 'width': 170, 'x': 0, 'y': 10},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_usage'},
                                      {   'align': 'left',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': '12px Arial',
                                          'format': '',
                                          'group': 1,
                                          'id': 2,
                                          'name': 'text',
                                          'rect': {'height': 20, 'width': 50, 'x': 5, 'y': 36},
                                          'refresh': 0,
                                          'sensor': True,
                                          'value': 'cpu'},
                                      {   'align': 'right',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': '12px Arial',
                                          'format': '{0}%',
                                          'group': 1,
                                          'id': 3,
                                          'name': 'text',
                                          'rect': {'height': 20, 'width': 37, 'x': 130, 'y': 36},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_usage'},
                                      {   'debug_frame': False,
                                          'fill': '#076b46',
                                          'format': '{1}',
                                          'group': 1,
                                          'id': 4,
                                          'name': 'bar_chart',
                                          'outline': '#00ff00',
                                          'points': 16,
                                          'rect': {'height': 40, 'width': 168, 'x': 0, 'y': 60},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'thickness': 8,
                                          'value': 'cpu_temp',
                                          'zoom': 17},
                                      {   'align': 'left',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': '12px Arial',
                                          'format': '',
                                          'group': 1,
                                          'id': 5,
                                          'name': 'text',
                                          'rect': {'height': 15, 'width': 35, 'x': 5, 'y': 103},
                                          'refresh': 1000,
                                          'sensor': False,
                                          'value': 'temp'},
                                      {   'align': 'right',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': '12px Arial',
                                          'format': '{0} {2}',
                                          'group': 1,
                                          'id': 6,
                                          'name': 'text',
                                          'rect': {'height': 15, 'width': 37, 'x': 130, 'y': 103},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'cpu_temp'},
                                      {   'debug_frame': True,
                                          'fill': '#ffffff',
                                          'format': '{12}',
                                          'group': 1,
                                          'horizontal': False,
                                          'id': 7,
                                          'name': 'bar_chart',
                                          'outline': '#ffffff',
                                          'points': 1,
                                          'rect': {'height': 35, 'width': 10, 'x': 90, 'y': 125},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'thickness': 10,
                                          'value': 'memory',
                                          'zoom': 0},
                                      {   'debug_frame': True,
                                          'fill': '#d7ecee',
                                          'format': '{10}',
                                          'group': 1,
                                          'horizontal': False,
                                          'id': 8,
                                          'name': 'bar_chart',
                                          'outline': '#ffffff',
                                          'points': 1,
                                          'rect': {'height': 35, 'width': 10, 'x': 10, 'y': 125},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'thickness': 10,
                                          'value': 'memory',
                                          'zoom': 0},
                                      {   'align': 'left',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': '11px Arial',
                                          'format': '{15}',
                                          'group': 1,
                                          'id': 9,
                                          'name': 'text',
                                          'rect': {'height': 15, 'width': 62, 'x': 104, 'y': 127},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'memory'},
                                      {   'align': 'left',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': '10px Arial',
                                          'format': '',
                                          'group': 1,
                                          'id': 10,
                                          'name': 'text',
                                          'rect': {'height': 16, 'width': 30, 'x': 105, 'y': 148},
                                          'refresh': 1000,
                                          'sensor': False,
                                          'value': 'swap'},
                                      {   'align': 'left',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': '10px Arial',
                                          'format': '{14}',
                                          'group': 1,
                                          'id': 11,
                                          'name': 'text',
                                          'rect': {'height': 15, 'width': 62, 'x': 25, 'y': 127},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'memory'},
                                      {   'align': 'left',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': '11px Arial',
                                          'format': '',
                                          'group': 1,
                                          'id': 12,
                                          'name': 'text',
                                          'rect': {'height': 16, 'width': 30, 'x': 25, 'y': 148},
                                          'refresh': 1000,
                                          'sensor': False,
                                          'value': 'used'},
                                      {   'area': True,
                                          'debug_frame': False,
                                          'fill': '#2332a6',
                                          'format': '{2}',
                                          'group': 1,
                                          'id': 13,
                                          'name': 'line_chart',
                                          'outline': '#0033ff',
                                          'points': 60,
                                          'rect': {'height': 35, 'width': 170, 'x': 0, 'y': 164},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'network_enp4s0'},
                                      {   'debug_frame': False,
                                          'fill': '#7a23f7',
                                          'format': '{1}',
                                          'group': 1,
                                          'horizontal': True,
                                          'id': 14,
                                          'name': 'bar_chart',
                                          'outline': '#37139c',
                                          'points': 1,
                                          'rect': {'height': 10, 'width': 170, 'x': 0, 'y': 201},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'thickness': 15,
                                          'value': 'network_enp4s0',
                                          'zoom': 0},
                                      {   'align': 'left',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': '12px Arial',
                                          'format': '',
                                          'group': 1,
                                          'id': 15,
                                          'name': 'text',
                                          'rect': {'height': 15, 'width': 15, 'x': 5, 'y': 212},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'rx'},
                                      {   'align': 'right',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': '12px Arial',
                                          'format': '{15}',
                                          'group': 1,
                                          'id': 16,
                                          'name': 'text',
                                          'rect': {'height': 15, 'width': 80, 'x': 90, 'y': 212},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'network_enp4s0'},
                                      {   'area': True,
                                          'debug_frame': False,
                                          'fill': '#a855f7',
                                          'format': '{5}',
                                          'group': 1,
                                          'id': 17,
                                          'name': 'line_chart',
                                          'outline': '#7c3aed',
                                          'points': 60,
                                          'rect': {'height': 35, 'width': 170, 'x': 0, 'y': 245},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'network_enp4s0'},
                                      {   'debug_frame': False,
                                          'fill': '#ff0091',
                                          'format': '{4}',
                                          'group': 1,
                                          'horizontal': True,
                                          'id': 18,
                                          'name': 'bar_chart',
                                          'outline': '#f5054d',
                                          'points': 1,
                                          'rect': {'height': 10, 'width': 170, 'x': 0, 'y': 282},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'thickness': 15,
                                          'value': 'network_enp4s0',
                                          'zoom': 0},
                                      {   'align': 'left',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': '12px Arial',
                                          'format': '',
                                          'group': 1,
                                          'id': 19,
                                          'name': 'text',
                                          'rect': {'height': 15, 'width': 15, 'x': 5, 'y': 293},
                                          'refresh': 1000,
                                          'sensor': False,
                                          'value': 'tx'},
                                      {   'align': 'right',
                                          'color': '#00d4ff',
                                          'debug_frame': False,
                                          'font': '12px Arial',
                                          'format': '{16}',
                                          'group': 1,
                                          'id': 20,
                                          'name': 'text',
                                          'rect': {'height': 15, 'width': 80, 'x': 90, 'y': 293},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'network_enp4s0'}]},
                   {   'background': '#000000',
                       'duartion': 0,
                       'duration': 60000,
                       'id': 3,
                       'led_config': {'intensity': 3, 'speed': 3, 'theme': 3},
                       'name': 'Screen 3 Date and Time',
                       'widgets': [   {   'align': 'center',
                                          'color': '#ffffff',
                                          'debug_frame': False,
                                          'font': '30px Arial',
                                          'format': '{4}',
                                          'group': 1,
                                          'id': 1,
                                          'name': 'text',
                                          'rect': {'height': 32, 'width': 170, 'x': 0, 'y': 40},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'calendar'},
                                      {   'align': 'center',
                                          'color': '#ffffff',
                                          'debug_frame': False,
                                          'font': '30px Arial',
                                          'format': '{6}',
                                          'group': 1,
                                          'id': 2,
                                          'name': 'text',
                                          'rect': {'height': 50, 'width': 170, 'x': 0, 'y': 100},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'calendar'},
                                      {   'align': 'center',
                                          'color': '#ffffff',
                                          'debug_frame': False,
                                          'font': '30px Arial',
                                          'format': '{3}',
                                          'group': 1,
                                          'id': 3,
                                          'name': 'text',
                                          'rect': {'height': 32, 'width': 170, 'x': 0, 'y': 145},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'calendar'},
                                      {   'align': 'center',
                                          'color': '#ffffff',
                                          'debug_frame': False,
                                          'font': '30px Arial',
                                          'format': '{8}',
                                          'group': 1,
                                          'id': 4,
                                          'name': 'text',
                                          'rect': {'height': 30, 'width': 170, 'x': 0, 'y': 190},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'calendar'},
                                      {   'align': 'center',
                                          'color': '#ffffff',
                                          'debug_frame': False,
                                          'font': '30px Arial',
                                          'format': '{1} {3}',
                                          'group': 1,
                                          'id': 5,
                                          'name': 'text',
                                          'rect': {'height': 40, 'width': 170, 'x': 0, 'y': 250},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'clock'}]},
                   {   'background': '#000000',
                       'duartion': 0,
                       'duration': 60000,
                       'id': 4,
                       'name': 'Screen 4 Weather',
                       'widgets': [   {   'align': 'center',
                                          'color': '#ffffff',
                                          'debug_frame': False,
                                          'font': '22px Arial',
                                          'format': '{7}',
                                          'group': 1,
                                          'id': 1,
                                          'name': 'text',
                                          'rect': {'height': 25, 'width': 170, 'x': 0, 'y': 10},
                                          'refresh': 1000,
                                          'sensor': False,
                                          'value': 'Weather'},
                                      {   'color': '#ffffff',
                                          'debug_frame': False,
                                          'format': '{4}',
                                          'group': 1,
                                          'id': 2,
                                          'name': 'weather_icon',
                                          'rect': {'height': 70, 'width': 70, 'x': 10, 'y': 40},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'type': 'weather',
                                          'value': 'current_weather_nyc'},
                                      {   'align': 'right',
                                          'color': '#ffffff',
                                          'debug_frame': False,
                                          'font': '25px Arial',
                                          'format': '{7}{8}',
                                          'group': 1,
                                          'id': 3,
                                          'name': 'text',
                                          'rect': {'height': 50, 'width': 70, 'x': 90, 'y': 60},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'current_weather_nyc'},
                                      {   'align': 'center',
                                          'color': '#ffffff',
                                          'debug_frame': False,
                                          'font': 'bold 18px Arial',
                                          'format': '{5}',
                                          'group': 1,
                                          'id': 4,
                                          'name': 'text',
                                          'rect': {'height': 26, 'width': 170, 'x': 0, 'y': 110},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'current_weather_nyc'},
                                      {   'align': 'left',
                                          'color': '#ffffff',
                                          'debug_frame': False,
                                          'font': '18px Arial',
                                          'format': 'H:{11}{12}',
                                          'group': 1,
                                          'id': 5,
                                          'name': 'text',
                                          'rect': {'height': 24, 'width': 70, 'x': 5, 'y': 140},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'today_weather_nyc'},
                                      {   'align': 'right',
                                          'color': '#ffffff',
                                          'debug_frame': False,
                                          'font': '18px Arial',
                                          'format': 'L:{9}{10}',
                                          'group': 1,
                                          'id': 6,
                                          'name': 'text',
                                          'rect': {'height': 24, 'width': 75, 'x': 85, 'y': 140},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'today_weather_nyc'},
                                      {   'color': '#ffffff',
                                          'debug_frame': False,
                                          'format': '{15}',
                                          'group': 1,
                                          'id': 7,
                                          'name': 'weather_icon',
                                          'rect': {'height': 50, 'width': 50, 'x': 20, 'y': 180},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'type': 'winddirection',
                                          'value': 'current_weather_nyc'},
                                      {   'align': 'left',
                                          'color': '#ffffff',
                                          'debug_frame': False,
                                          'font': '14px Arial',
                                          'format': '{13} {14}',
                                          'group': 1,
                                          'id': 8,
                                          'name': 'text',
                                          'rect': {'height': 18, 'width': 80, 'x': 80, 'y': 190},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'current_weather_nyc'},
                                      {   'align': 'left',
                                          'color': '#ffffff',
                                          'debug_frame': False,
                                          'font': '14px Arial',
                                          'format': '{15}{16}{17}',
                                          'group': 1,
                                          'id': 9,
                                          'name': 'text',
                                          'rect': {'height': 18, 'width': 80, 'x': 80, 'y': 210},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'current_weather_nyc'},
                                      {   'align': 'center',
                                          'color': '#ffffff',
                                          'debug_frame': False,
                                          'font': '16px Arial',
                                          'format': '{18} {19}',
                                          'group': 1,
                                          'id': 10,
                                          'name': 'text',
                                          'rect': {'height': 20, 'width': 150, 'x': 10, 'y': 275},
                                          'refresh': 1000,
                                          'sensor': True,
                                          'value': 'today_weather_nyc'},
                                      {   'align': 'center',
                                          'color': '#ffffff',
                                          'debug_frame': False,
                                          'font': '15px Arial',
                                          'format': '',
                                          'group': 1,
                                          'id': 11,
                                          'name': 'text',
                                          'rect': {'height': 20, 'width': 150, 'x': 10, 'y': 250},
                                          'refresh': 1000,
                                          'sensor': False,
                                          'value': 'Precipitation'}]}]}
